import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Footer } from "@/components/Footer";
import { Provider } from "@/util/Providers";
export const metadata: Metadata = {
  title: "shop.co",
  description: "Generated by create next app",
  icons: "../assets/svgs/logo.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <Provider>
          <main className="overflow-x-hidden">
            <NavBar />
            {children}
            <Footer />
          </main>
        </Provider>
      </body>
    </html>
  );
}
